---
name: Service worker version check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  check-sw-version:
    name: Check service worker cache version
    runs-on: ubuntu-latest
    steps:
      # renovate: datasource=github-tags depName=actions/checkout
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          fetch-depth: 0

      # renovate: datasource=github-tags depName=actions/setup-node
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          # renovate: datasource=node-version depName=node
          node-version: "24"

      - name: Check service worker cache version
        run: npm run check:sw-version
